## Numpy Arrays

In [1]:
# importing the numpy library
import numpy as np

In [4]:
# converting a 1D list into a numpy array

a = np.array([2,3,4,5])
print("Array1:",a)
    
# converting a 2D list into a numpy array
a = np.array([[1,2,3],[9,6,5], [12,1,4]])
print("Array2:")
print(a)

Array1: [2 3 4 5]
Array2:
[[ 1  2  3]
 [ 9  6  5]
 [12  1  4]]


In [5]:
# creating a numpy array from 0, upto a given number

a = np.arange(14)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [10]:
# creating a NULL matrix, or an array of zeroes of specified dimensions

a = np.zeros([2,3],dtype=int)
print("Array of zeroes:")
print(a)

# creating an array of ones of specified dimensions

a = np.ones([3,4], dtype=int)
print("Array of ones: ")
print(a)

# creating an array of same number of specified dimensions

a = np.full([3,2], 7, dtype=int)
print("Array of specified number: ")
print(a)

# creating an identity matrix of specified dimensions

a = np.eye(3,3, dtype=int)
print("Identity matrix: ")
print(a)

Array of zeroes:
[[0 0 0]
 [0 0 0]]
Array of ones: 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Array of specified number: 
[[7 7]
 [7 7]
 [7 7]]
Identity matrix: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [12]:
# creating an array of elements which are equally distributed within a range for a specific number of elements

a = np.linspace(1, 20, 6)
print("Linspace array:")
print(a)

Linspace array:
[ 1.   4.8  8.6 12.4 16.2 20. ]


In [27]:
# accessing elements in a numpy array

a = np.array([[1,2,3],[9,6,5], [12,1,4], [2,6,8]])
print(a[0, 2])
print(a[0:, :2])
print(a[:2, 1:])

3
[[ 1  2]
 [ 9  6]
 [12  1]
 [ 2  6]]
[[2 3]
 [6 5]]


In [30]:
# printing the number of dimensions of a numpy array

print("No.of dimensions of a:", a.ndim)

# printing the dimensions of a numpy array

print("Dimensions of a:", a.shape)

# print the data type of the elements of the array

print("Data type of elements of a:", a.dtype)

# change the data type of the elements of the array

print("Array with floating point numbers:")
print(a.astype(np.float64))

# reshaping the array to a specified dimensions

print("Reshaped array: ")
print(a.reshape(4,3))

No.of dimensions of a: 2
Dimensions of a: (3, 4)
Data type of elements of a: int64
Array with floating point numbers:
[[ 1.  2.  3.  9.]
 [ 6.  5. 12.  1.]
 [ 4.  2.  6.  8.]]
Reshaped array: 
[[ 1  2  3]
 [ 9  6  5]
 [12  1  4]
 [ 2  6  8]]


In [31]:
# Finding minimum and maximum elements in an array

a = np.array([3,45,6,2,1,54,6])
print("Maximum element is:", a.max())

print("Minimum element is:", a.min())

# Finding sum of the elements of the array

print("Sum of array elements is:", a.sum())

# Finding mean, standard deviation and variance of an array

print("Mean of array elements:", a.mean())

print("Standard deviation of array elements:", a.std())

print("Variance of array elements:", a.var())

Maximum element is: 54
Minimum element is: 1
Sum of array elements is: 117
Mean of array elements: 16.714285714285715
Standard deviation of array elements: 20.946968998021685
Variance of array elements: 438.7755102040816
